-- Create a table to store Clash of Clans API keys mapped to IP addresses
create table public.clash_api_keys (
  id bigint generated by default as identity primary key,
  ip_address text not null unique,
  key_id text, -- The ID of the key from Clash API (optional, but good for reference)
  key text not null, -- The actual JWT token
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.clash_api_keys enable row level security;

-- Create a policy that allows the service role (our Edge Functions) to do everything
-- We don't want public users to access this table directly!
create policy "Enable all access for service role only"
on public.clash_api_keys
for all
to service_role
using (true)
with check (true);

-- Create an index on IP address for faster lookups
create index clash_api_keys_ip_address_idx on public.clash_api_keys (ip_address);
