// supabase/functions/_shared/clashApi.ts
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

// Constants for Clash of Clans Developer Portal
const DEV_SITE_URL = 'https://developer.clashofclans.com';
const LOGIN_URL = `${DEV_SITE_URL}/api/login`;
const KEY_LIST_URL = `${DEV_SITE_URL}/api/apikey/list`;
const KEY_CREATE_URL = `${DEV_SITE_URL}/api/apikey/create`;
const KEY_REVOKE_URL = `${DEV_SITE_URL}/api/apikey/revoke`;

interface ClashApiError extends Error {
  statusCode?: number;
  type?: string;
}

// Helper to get the current public IP of this Edge Function
async function getCurrentIp(): Promise<string> {
  const response = await fetch('https://api.ipify.org?format=json');
  const data = await response.json();
  return data.ip;
}

// Helper to login to Clash Developer Portal
async function loginToDevPortal(email: string, pass: string): Promise<string> {
  const response = await fetch(LOGIN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password: pass })
  });

  if (!response.ok) {
    throw new Error(`Failed to login to Clash Developer Portal: ${response.statusText}`);
  }

  // The session cookie is set in the response headers
  // We need to extract it to use for subsequent requests
  // Note: In Deno/Edge Functions, we might need to handle cookies manually if fetch doesn't persist them automatically across requests
  // But usually, we get a JSON response with a temporary token or we rely on the Set-Cookie header.
  // Actually, the Clash portal uses a cookie based auth.
  // Let's check the response body first.
  const data = await response.json();
  // Usually it returns a status. The important part is the 'set-cookie' header.
  
  // However, fetch in Deno doesn't automatically store cookies in a jar like a browser.
  // We need to grab the cookie string.
  const cookie = response.headers.get('set-cookie');
  if (!cookie) {
    throw new Error('Login successful but no session cookie received.');
  }
  return cookie;
}

// Helper to create a new key
async function createKey(cookie: string, name: string, description: string, ip: string) {
  const response = await fetch(KEY_CREATE_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': cookie
    },
    body: JSON.stringify({
      name,
      description,
      cidrRanges: [ip],
      scopes: ['clash'] // Usually 'clash' or null
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to create key: ${text}`);
  }

  return await response.json();
}

// Helper to list keys and delete old ones if necessary
async function rotateKeys(cookie: string) {
  const response = await fetch(KEY_LIST_URL, {
    method: 'POST', // Yes, list is often a POST in this API
    headers: { 'Content-Type': 'application/json', 'Cookie': cookie },
    body: JSON.stringify({})
  });

  if (response.ok) {
    const data = await response.json();
    const keys = data.keys || [];
    
    // If we have too many keys (limit is usually 10), delete the oldest ones
    if (keys.length >= 8) {
      // Sort by creation or just take the first ones? The API doesn't always give dates.
      // We'll just delete the first one found to make room.
      const keyToDelete = keys[0];
      await fetch(KEY_REVOKE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Cookie': cookie },
        body: JSON.stringify({ id: keyToDelete.id })
      });
    }
  }
}

// Exported token resolver (creates its own Supabase client)
export async function getValidToken(): Promise<string> {
  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
  const supabase = createClient(supabaseUrl, supabaseKey);
  // 1. Get current IP
  const currentIp = await getCurrentIp();
  console.log(`Current Edge Function IP: ${currentIp}`);

  // 2. Check DB for existing key
  const { data: existingKey } = await supabase
    .from('clash_api_keys')
    .select('key')
    .eq('ip_address', currentIp)
    .single();

  if (existingKey) {
    console.log('Found existing key in DB');
    return existingKey.key;
  }

  console.log('No key found for this IP. Logging in to create new key...');

  // 3. Login and Create New Key
  const email = Deno.env.get('CLASH_DEV_EMAIL');
  const password = Deno.env.get('CLASH_DEV_PASSWORD');

  if (!email || !password) {
    throw new Error('Missing CLASH_DEV_EMAIL or CLASH_DEV_PASSWORD env vars');
  }

  const cookie = await loginToDevPortal(email, password);
  
  // Clean up old keys if needed
  await rotateKeys(cookie);

  // Create new key
  const keyData = await createKey(cookie, 'FireCastle AutoKey', 'Auto-generated by Supabase Edge Function', currentIp);
  const newKey = keyData.key.key; // Structure is usually { key: { key: "..." } } or similar, need to verify

  // 4. Save to DB
  await supabase.from('clash_api_keys').insert({
    ip_address: currentIp,
    key: newKey,
    key_id: keyData.key.id
  });

  return newKey;
}

export async function fetchFromClashAPI(endpoint: string): Promise<any> {
  // Initialize Supabase Client
  const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? '';
  const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    // Get a valid token (cached or new)
    const apiToken = await getValidToken();

    // Make the actual API call
    const response = await fetch(`https://api.clashofclans.com/v1${endpoint}`, {
      headers: {
        'Authorization': `Bearer ${apiToken}`,
        'Accept': 'application/json'
      },
      signal: AbortSignal.timeout(10000)
    });

    if (!response.ok) {
      const error = new Error(`API Error: ${response.statusText}`) as ClashApiError;
      error.statusCode = response.status;
      
      // If 403 Forbidden, it might mean the IP changed or key is invalid.
      // We could try to delete the key from DB and retry once?
      // For now, just throw.
      
      throw error;
    }

    return await response.json();
  } catch (error: any) {
    console.error('Clash API Error:', error);
    throw error;
  }
}

export function corsHeaders(origin: string = '*') {
  return {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Content-Type': 'application/json'
  };
}
